export const BRICKBALL_ANSWERS = [
    "Yes.",
    "No.",
    "Definitely.",
    "Absolutely not.",
    "Without a doubt.",
    "Ask again later.",
    "It is certain.",
    "Very unlikely.",
    "Signs point to yes.",
    "Don’t count on it.",
    "Probably.",
    "Probably not.",
    "As I see it, yes.",
    "My sources say no.",
    "Most likely.",
    "Outlook not so good.",
    "Cannot predict now.",
    "You may rely on it.",
    "Better not tell you now.",
    "Yes — but be careful.",
    "No — and you’ll thank me later.",
    "I wouldn’t if I were you.",
    "Trust your instincts — yes.",
    "Not now.",
    "Absolutely.",
    "I’d say so.",
    "Nope.",
    "Not a chance.",
    "Wait for it.",
    "Sure thing.",
    "Unclear — try again.",
    "In your dreams.",
    "The stars say yes.",
    "Cosmic forces say no.",
    "Looks good.",
    "The outlook is hazy.",
    "Highly probable.",
    "Hmm... unlikely.",
    "Could go either way.",
    "You already know the answer.",
    "Only if you're ready.",
    "Not today.",
    "Definitely not right now.",
    "Green light.",
    "Red flag!",
    "The signs say no.",
    "Proceed with caution.",
    "Flip a coin.",
    "Maybe — but don’t push it.",
    "Yes, but only just."
]